# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a4931503c6c9e7e21db80332f537b9e50c470fd0b0b1a3da5cc066cb424013088de78a1d9e02d870cd9785b294a548da3d40f44afa291efe34ef6832c8c13c7

test:
  secret_key_base: f735e8b2624f8d510b4401ad1c85be3f668e32fdd3b63af4044ce508dc5d3cf03328fe647a4f6a2e1e16d6c903303a60f64bb678cdc3e285c84c79e901ace58e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
